version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./examples/mnist/runs:/app/examples/mnist/runs
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    command: /bin/bash
