paths:
  base_dir: "./runs/mnist"

server:
  host: "localhost"
  port: 8080  # Note: "port", not "post"
  max_request_size: 104857600  # 100MB

training:
  num_rounds: 2
  min_clients: 3
  min_completion_rate: 0.8
  round_timeout: 300
  
logging:
  level: "INFO"
  color: true
  output: "both"